model_params:
  name: 'MlpConditionalVAE'
  in_channels: 3
  conditional_dims: 1

exp_params:
  adam_lr: 0.001
  kld_weight: 0.00025
  manual_seed: 1265
  validate_after_epochs: 10
  batch_size: 512

trainer_params:
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "MlpConditionalVAE"

network_params:
  data_feature_dim: [3, 3]
  latent_dim: 64
  conditional_dim: [1, 3]

data_params:
  data_path: "data/training_LARGE.root"
  train_batch_size: 512
  val_batch_size: 512
#  num_workers: 1


generate_params:
  checkpoint_path: "logs/MlpConditionalVAE/version_63/checkpoints/last.ckpt"
  pdf_prefix: "logs/MlpConditionalVAE/version_63/samples/gen_res"
#  total_samples: 20000
  batch_size: 512
  predict_batch_size: 512
  kld_weight: 0.00025


plotter:
  check_file: 'logs/data_check.pdf'
  ranges:
    px_min: -3
    px_max: 3
    py_min: -3
    py_max: 3
    pz_min: -5
    pz_max: 5000
  unit: '[GeV]'
